### PR TITLE
Update node-sass to 3.0.0

### PR DESCRIPTION
**Pull request by mbarlock**
I can't believe this updated under my nose like that...

Also as a note, node-sass 3.0.0 no longer supports image-path

### CODE REVIEW

**Comment by mbarlock** [comment]
#31

**Comment by jking90** [comment]
No worries, its nice to have a version published with 2.1.1, in case someone needs it.

**Comment by jking90** [comment]
@mbarlock would you be interested in being an official contributor (push access)

**Comment by jking90** [comment]
Published as v2.7.0

**Comment by mbarlock** [comment]
@jking90 sure that'd be great!

**Comment by jking90** [comment]
Also, @mbarlock I use git flow. If you're not familiar with it, you can read up on it [here](http://nvie.com/posts/a-successful-git-branching-model/). And only merge into master during the release process.

**Pull request merged**
