### PR TITLE
exclude node-sass v3.4.1

### PR DESCRIPTION
**Pull request by nfriedly**
https://github.com/sass/node-sass/issues/1219 is killing me. Broken in v3.4.1 and expected to be fixed in v3.4.2

### CODE REVIEW

**Comment by jking90** [comment]
@nfriedly can you fix the failing test?

**Comment by nfriedly** [comment]
Um, I can take a look.. although I doubt it's related to this change.

On Wed, Oct 28, 2015 at 4:17 PM, Jimmy King <notifications@github.com>
wrote:

> @nfriedly <https://github.com/nfriedly> can you fix the failing test?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jking90/docpad-plugin-nodesass/pull/42#issuecomment-151992685>
> .
>



-- 
Nathan Friedly
Minister, JavaScript Ninjaneer
http://nfriedly.com

**Comment by jking90** [comment]
@nfriedly Looked into that test and its just the bourbon / neat test thats failing. Since thats deprecated I just removed the test

**Comment by jking90** [comment]
Published in v2.8.1

**Comment by nfriedly** [comment]
Thanks!

**Pull request merged**
